In [2]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [3]:
data=pd.read_csv("C:\\Users\\user\\Desktop\\datas\\ticket_08_2017.csv")

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3071: DtypeWarning: Columns (5) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


In [4]:
data

sync_ticket_id  sync_tkt_owner_id  sync_tkt_device_id  \
0               402854           15050034                  34   
1               402855           15050034                  34   
2               402856           15050034                  34   
3               402894           15050034                  34   
4               402966           15050034                  34   
...                ...                ...                 ...   
217383          641842           15050217                 234   
217384          641843           15050217                 234   
217385          641844           15050217                 234   
217386          641845           15050217                 234   
217387          641846           15050217                 234   

       sync_tkt_employee_id sync_tkt_vehicle_id sync_tkt_route_code  \
0                      EMP1        KL-06-D-9858                9858   
1                      EMP1        KL-06-D-9858                9858   
2                      EMP1        KL-06-D-9858                9858   
3                      EMP1        KL-06-D-9858                9858   
4                      EMP1        KL-06-D-9858                9858   
...                     ...                 ...                 ...   
217383                 EMP1        KL-35-F-7257                  56   
217384                 EMP1        KL-35-F-7257                  56   
217385                 EMP1        KL-35-F-7257                  56   
217386                 EMP1        KL-35-F-7257                  56   
217387                 EMP1        KL-35-F-7257                  56   

       sync_tkt_route_name  sync_tkt_schedule_no  sync_tkt_trip_no  \
0             CHRY-NEDKNDM                     1                 2   
1             CHRY-NEDKNDM                     1                 2   
2             CHRY-NEDKNDM                     1                 2   
3             CHRY-NEDKNDM                     1                 2   
4             CHRY-NEDKNDM                     1                 2   
...                    ...                   ...               ...   
217383         KTYM-CHRTLA                     1                 2   
217384         KTYM-CHRTLA                     1                 2   
217385         KTYM-CHRTLA                     1                 2   
217386         KTYM-CHRTLA                     1                 2   
217387         KTYM-CHRTLA                     1                 2   

       sync_tkt_start_stage_name  ...  sync_tkt_card_id  \
0                      KATTAPANA  ...  TK00100100004368   
1                      KATTAPANA  ...  TK02150000033463   
2                      KATTAPANA  ...  TK02150000026031   
3                         SWARAJ  ...  TK02150000035257   
4                     MATTUKATTA  ...  TK02150000025328   
...                          ...  ...               ...   
217383                  CHERTALA  ...  TK02150000024005   
217384                  CHERTALA  ...  TK02150000016884   
217385                  CHERTALA  ...  TK02150000028130   
217386                  CHERTALA  ...  TK02150000018824   
217387                  CHERTALA  ...  TK02150000024557   

       sync_tkt_card_balance_amount  sync_tkt_card_prv_balance_amount  \
0                             81.15                             94.75   
1                             85.60                            100.00   
2                            268.00                            299.20   
3                             90.40                            115.20   
4                             72.00                             94.40   
...                             ...                               ...   
217383                        58.80                             80.05   
217384                        73.25                             95.35   
217385                        33.60                             53.15   
217386                        80.30                            102.40   
217387               

In [4]:
data.head()

sync_ticket_id  sync_tkt_owner_id  sync_tkt_device_id sync_tkt_employee_id  \
0          402854           15050034                  34                 EMP1   
1          402855           15050034                  34                 EMP1   
2          402856           15050034                  34                 EMP1   
3          402894           15050034                  34                 EMP1   
4          402966           15050034                  34                 EMP1   

  sync_tkt_vehicle_id sync_tkt_route_code sync_tkt_route_name  \
0        KL-06-D-9858                9858        CHRY-NEDKNDM   
1        KL-06-D-9858                9858        CHRY-NEDKNDM   
2        KL-06-D-9858                9858        CHRY-NEDKNDM   
3        KL-06-D-9858                9858        CHRY-NEDKNDM   
4        KL-06-D-9858                9858        CHRY-NEDKNDM   

   sync_tkt_schedule_no  sync_tkt_trip_no sync_tkt_start_stage_name  ...  \
0                     1                 2                 KATTAPANA  ...   
1                     1                 2                 KATTAPANA  ...   
2                     1                 2                 KATTAPANA  ...   
3                     1                 2                    SWARAJ  ...   
4                     1                 2                MATTUKATTA  ...   

   sync_tkt_card_id sync_tkt_card_balance_amount  \
0  TK00100100004368                        81.15   
1  TK02150000033463                        85.60   
2  TK02150000026031                       268.00   
3  TK02150000035257                        90.40   
4  TK02150000025328                        72.00   

   sync_tkt_card_prv_balance_amount  sync_tkt_pass_no        sync_tkt_date  \
0                             94.75                 0  2017-08-01 08:08:00   
1                            100.00                 0  2017-08-01 08:09:30   
2                            299.20                 0  2017-08-01 08:08:34   
3                            115.20                 0  2017-08-01 08:24:49   
4                             94.40                 0  2017-08-01 08:33:56   

   sync_tkt_created_date  sync_location_name  sync_tkt_total_trn  \
0    2017-08-01 08:08:11              Ticket                  36   
1    2017-08-01 08:09:40              Ticket                  38   
2    2017-08-01 08:08:43              Ticket                  37   
3    2017-08-01 08:24:59              Ticket                  39   
4    2017-08-01 08:34:05              Ticket                  40   

   sync_tkt_pending_trn  sync_tkt_approval  
0                     0                  0  
1                     0                  0  
2                     0                  0  
3                     0                  0  
4                     0                  0  

[5 rows x 41 columns]

In [5]:
data.tail()

sync_ticket_id  sync_tkt_owner_id  sync_tkt_device_id  \
217383          641842           15050217                 234   
217384          641843           15050217                 234   
217385          641844           15050217                 234   
217386          641845           15050217                 234   
217387          641846           15050217                 234   

       sync_tkt_employee_id sync_tkt_vehicle_id sync_tkt_route_code  \
217383                 EMP1        KL-35-F-7257                  56   
217384                 EMP1        KL-35-F-7257                  56   
217385                 EMP1        KL-35-F-7257                  56   
217386                 EMP1        KL-35-F-7257                  56   
217387                 EMP1        KL-35-F-7257                  56   

       sync_tkt_route_name  sync_tkt_schedule_no  sync_tkt_trip_no  \
217383         KTYM-CHRTLA                     1                 2   
217384         KTYM-CHRTLA                     1                 2   
217385         KTYM-CHRTLA                     1                 2   
217386         KTYM-CHRTLA                     1                 2   
217387         KTYM-CHRTLA                     1                 2   

       sync_tkt_start_stage_name  ...  sync_tkt_card_id  \
217383                  CHERTALA  ...  TK02150000024005   
217384                  CHERTALA  ...  TK02150000016884   
217385                  CHERTALA  ...  TK02150000028130   
217386                  CHERTALA  ...  TK02150000018824   
217387                  CHERTALA  ...  TK02150000024557   

       sync_tkt_card_balance_amount  sync_tkt_card_prv_balance_amount  \
217383                        58.80                             80.05   
217384                        73.25                             95.35   
217385                        33.60                             53.15   
217386                        80.30                            102.40   
217387                        31.55                             37.50   

        sync_tkt_pass_no        sync_tkt_date  sync_tkt_created_date  \
217383                 0  2017-08-31 16:47:56    2017-09-05 13:17:51   
217384                 0  2017-08-31 16:40:31    2017-09-05 13:17:51   
217385                 0  2017-08-31 16:39:35    2017-09-05 13:17:51   
217386                 0  2017-08-31 16:35:54    2017-09-05 13:17:50   
217387                 0  2017-08-31 16:31:54    2017-09-05 13:17:50   

        sync_location_name  sync_tkt_total_trn  sync_tkt_pending_trn  \
217383              Ticket                   9                     8   
217384              Ticket                   8                     7   
217385              Ticket                   7                     6   
217386              Ticket                   6                     5   
217387              Ticket                   5                     4   

        sync_tkt_approval  
217383                  0  
217384                  0  
217385                  0  
217386                  0  
217387                  0  

[5 rows x 41 columns]

In [6]:
data.describe

<bound method NDFrame.describe of         sync_ticket_id  sync_tkt_owner_id  sync_tkt_device_id  \
0               402854           15050034                  34   
1               402855           15050034                  34   
2               402856           15050034                  34   
3               402894           15050034                  34   
4               402966           15050034                  34   
...                ...                ...                 ...   
217383          641842           15050217                 234   
217384          641843           15050217                 234   
217385          641844           15050217                 234   
217386          641845           15050217                 234   
217387          641846           15050217                 234   

       sync_tkt_employee_id sync_tkt_vehicle_id sync_tkt_route_code  \
0                      EMP1        KL-06-D-9858                9858   
1                      EMP1        KL-06-D-

In [5]:
print(data)

        sync_ticket_id  sync_tkt_owner_id  sync_tkt_device_id  \
0               402854           15050034                  34   
1               402855           15050034                  34   
2               402856           15050034                  34   
3               402894           15050034                  34   
4               402966           15050034                  34   
...                ...                ...                 ...   
217383          641842           15050217                 234   
217384          641843           15050217                 234   
217385          641844           15050217                 234   
217386          641845           15050217                 234   
217387          641846           15050217                 234   

       sync_tkt_employee_id sync_tkt_vehicle_id sync_tkt_route_code  \
0                      EMP1        KL-06-D-9858                9858   
1                      EMP1        KL-06-D-9858                9858   
2     

In [8]:
print(data.columns)

Index(['sync_ticket_id', 'sync_tkt_owner_id', 'sync_tkt_device_id',
       'sync_tkt_employee_id', 'sync_tkt_vehicle_id', 'sync_tkt_route_code',
       'sync_tkt_route_name', 'sync_tkt_schedule_no', 'sync_tkt_trip_no',
       'sync_tkt_start_stage_name', 'sync_tkt_end_stage_name', 'sync_tkt_uid',
       'sync_tkt_full_count', 'sync_tkt_half_count', 'sync_tkt_student_count',
       'sync_tkt_ph_count', 'sync_tkt_pass_count', 'sync_tkt_luggage_count',
       'sync_tkt_warrant_count', 'sync_tkt_full_amount',
       'sync_tkt_half_amount', 'sync_tkt_student_amount', 'sync_tkt_ph_amount',
       'sync_tkt_pass_amount', 'sync_tkt_luggage_amount',
       'sync_tkt_warrant_amount', 'sync_tkt_updown_trip', 'sync_tkt_ticket_no',
       'sync_tkt_total_amount', 'sync_tkt_discount_amount',
       'sync_tkt_card_ticket_status', 'sync_tkt_card_id',
       'sync_tkt_card_balance_amount', 'sync_tkt_card_prv_balance_amount',
       'sync_tkt_pass_no', 'sync_tkt_date', 'sync_tkt_created_date',
       's

In [6]:
df1=data.iloc[:,6:13]
print(df1.columns)

Index(['sync_tkt_route_name', 'sync_tkt_schedule_no', 'sync_tkt_trip_no',
       'sync_tkt_start_stage_name', 'sync_tkt_end_stage_name', 'sync_tkt_uid',
       'sync_tkt_full_count'],
      dtype='object')


In [7]:
print(df1['sync_tkt_route_name'])

0         CHRY-NEDKNDM
1         CHRY-NEDKNDM
2         CHRY-NEDKNDM
3         CHRY-NEDKNDM
4         CHRY-NEDKNDM
              ...     
217383     KTYM-CHRTLA
217384     KTYM-CHRTLA
217385     KTYM-CHRTLA
217386     KTYM-CHRTLA
217387     KTYM-CHRTLA
Name: sync_tkt_route_name, Length: 217388, dtype: object


In [8]:
print(df1['sync_tkt_schedule_no'])

0         1
1         1
2         1
3         1
4         1
         ..
217383    1
217384    1
217385    1
217386    1
217387    1
Name: sync_tkt_schedule_no, Length: 217388, dtype: int64


In [9]:
print(df1['sync_tkt_trip_no'])

0         2
1         2
2         2
3         2
4         2
         ..
217383    2
217384    2
217385    2
217386    2
217387    2
Name: sync_tkt_trip_no, Length: 217388, dtype: int64


In [10]:
print(df1[ 'sync_tkt_start_stage_name'])

0          KATTAPANA
1          KATTAPANA
2          KATTAPANA
3             SWARAJ
4         MATTUKATTA
             ...    
217383      CHERTALA
217384      CHERTALA
217385      CHERTALA
217386      CHERTALA
217387      CHERTALA
Name: sync_tkt_start_stage_name, Length: 217388, dtype: object


In [11]:
print(df1[ 'sync_tkt_end_stage_name'])

0           MARUKULAM
1              PARAPU
2         KUTTIKANNAM
3         KUTTIKANNAM
4         KUTTIKANNAM
             ...     
217383      AALUMOODU
217384       KOTTAYAM
217385       ILLICKAL
217386       KOTTAYAM
217387      KATACHIRA
Name: sync_tkt_end_stage_name, Length: 217388, dtype: object


In [12]:
print(df1['sync_tkt_uid'])

0         2017-07-31 14:43:35
1         2017-07-31 14:43:35
2         2017-07-31 14:43:35
3         2017-07-31 14:43:35
4         2017-07-31 14:43:35
                 ...         
217383    2017-08-31 14:00:06
217384    2017-08-31 14:00:06
217385    2017-08-31 14:00:06
217386    2017-08-31 14:00:06
217387    2017-08-31 14:00:06
Name: sync_tkt_uid, Length: 217388, dtype: object


In [13]:
print(df1['sync_tkt_full_count'])

0         1
1         1
2         1
3         1
4         1
         ..
217383    1
217384    1
217385    1
217386    1
217387    1
Name: sync_tkt_full_count, Length: 217388, dtype: int64


In [14]:
df2=df1[['sync_tkt_route_name', 'sync_tkt_schedule_no', 'sync_tkt_trip_no',
       'sync_tkt_start_stage_name', 'sync_tkt_end_stage_name','sync_tkt_full_count']]
print(df2)

       sync_tkt_route_name  sync_tkt_schedule_no  sync_tkt_trip_no  \
0             CHRY-NEDKNDM                     1                 2   
1             CHRY-NEDKNDM                     1                 2   
2             CHRY-NEDKNDM                     1                 2   
3             CHRY-NEDKNDM                     1                 2   
4             CHRY-NEDKNDM                     1                 2   
...                    ...                   ...               ...   
217383         KTYM-CHRTLA                     1                 2   
217384         KTYM-CHRTLA                     1                 2   
217385         KTYM-CHRTLA                     1                 2   
217386         KTYM-CHRTLA                     1                 2   
217387         KTYM-CHRTLA                     1                 2   

       sync_tkt_start_stage_name sync_tkt_end_stage_name  sync_tkt_full_count  
0                      KATTAPANA               MARUKULAM                    1  

In [15]:
df2

sync_tkt_route_name  sync_tkt_schedule_no  sync_tkt_trip_no  \
0             CHRY-NEDKNDM                     1                 2   
1             CHRY-NEDKNDM                     1                 2   
2             CHRY-NEDKNDM                     1                 2   
3             CHRY-NEDKNDM                     1                 2   
4             CHRY-NEDKNDM                     1                 2   
...                    ...                   ...               ...   
217383         KTYM-CHRTLA                     1                 2   
217384         KTYM-CHRTLA                     1                 2   
217385         KTYM-CHRTLA                     1                 2   
217386         KTYM-CHRTLA                     1                 2   
217387         KTYM-CHRTLA                     1                 2   

       sync_tkt_start_stage_name sync_tkt_end_stage_name  sync_tkt_full_count  
0                      KATTAPANA               MARUKULAM                    1  
1                      KATTAPANA                  PARAPU                    1  
2                      KATTAPANA             KUTTIKANNAM                    1  
3                         SWARAJ             KUTTIKANNAM                    1  
4                     MATTUKATTA             KUTTIKANNAM                    1  
...                          ...                     ...                  ...  
217383                  CHERTALA               AALUMOODU                    1  
217384                  CHERTALA                KOTTAYAM                    1  
217385                  CHERTALA                ILLICKAL                    1  
217386                  CHERTALA                KOTTAYAM                    1  
217387                  CHERTALA               KATACHIRA                    1  

[217388 rows x 6 columns]

In [16]:
df3=df2.groupby(['sync_tkt_route_name','sync_tkt_schedule_no','sync_tkt_trip_no','sync_tkt_start_stage_name', 'sync_tkt_end_stage_name'],as_index=False).agg({ 'sync_tkt_full_count':'sum'})
df3

sync_tkt_route_name  sync_tkt_schedule_no  sync_tkt_trip_no  \
0            ANGLVLY-KTYM                     1                 1   
1            ANGLVLY-KTYM                     1                 1   
2            ANGLVLY-KTYM                     1                 1   
3            ANGLVLY-KTYM                     1                 1   
4            ANGLVLY-KTYM                     1                 1   
...                   ...                   ...               ...   
45745      VAIKOM-PNCHKAD                     3                 5   
45746      VAIKOM-PNCHKAD                     3                 6   
45747      VAIKOM-PNCHKAD                     3                 6   
45748      VAIKOM-PNCHKAD                     3                 7   
45749      VAIKOM-PNCHKAD                     3                 7   

      sync_tkt_start_stage_name sync_tkt_end_stage_name  sync_tkt_full_count  
0                         8MILE                MANIMALA                   13  
1                         8MILE                  PKALAM                    3  
2                     ALAMPALLY                   KPARA                    1  
3                     ALAMPALLY                MANIMALA                    1  
4                      CHETTEDA                MANIMALA                    3  
...                         ...                     ...                  ...  
45745                    VAIKOM              PUTANPALOM                    1  
45746                 KUMARAKOM                KOTTAYAM                    1  
45747                    VAIKOM              TALAYAZHOM                    1  
45748                    VAIKOM             KAVANATNKAR                    1  
45749                    VAIKOM                KOTTAYAM                    1  

[45750 rows x 6 columns]

In [17]:
df3.head()

sync_tkt_route_name  sync_tkt_schedule_no  sync_tkt_trip_no  \
0        ANGLVLY-KTYM                     1                 1   
1        ANGLVLY-KTYM                     1                 1   
2        ANGLVLY-KTYM                     1                 1   
3        ANGLVLY-KTYM                     1                 1   
4        ANGLVLY-KTYM                     1                 1   

  sync_tkt_start_stage_name sync_tkt_end_stage_name  sync_tkt_full_count  
0                     8MILE                MANIMALA                   13  
1                     8MILE                  PKALAM                    3  
2                 ALAMPALLY                   KPARA                    1  
3                 ALAMPALLY                MANIMALA                    1  
4                  CHETTEDA                MANIMALA                    3

In [18]:
df3.tail()

sync_tkt_route_name  sync_tkt_schedule_no  sync_tkt_trip_no  \
45745      VAIKOM-PNCHKAD                     3                 5   
45746      VAIKOM-PNCHKAD                     3                 6   
45747      VAIKOM-PNCHKAD                     3                 6   
45748      VAIKOM-PNCHKAD                     3                 7   
45749      VAIKOM-PNCHKAD                     3                 7   

      sync_tkt_start_stage_name sync_tkt_end_stage_name  sync_tkt_full_count  
45745                    VAIKOM              PUTANPALOM                    1  
45746                 KUMARAKOM                KOTTAYAM                    1  
45747                    VAIKOM              TALAYAZHOM                    1  
45748                    VAIKOM             KAVANATNKAR                    1  
45749                    VAIKOM                KOTTAYAM                    1

Look for is there any NAN values

In [19]:
df3.isnull().sum()

sync_tkt_route_name          0
sync_tkt_schedule_no         0
sync_tkt_trip_no             0
sync_tkt_start_stage_name    0
sync_tkt_end_stage_name      0
sync_tkt_full_count          0
dtype: int64

 Take sync_tkt_full_count as Y

In [20]:
Y=df3.iloc[:,[-1]].values #values is to be used, otherwise we get as dataframe
print(Y)

[[13]
 [ 3]
 [ 1]
 ...
 [ 1]
 [ 1]
 [ 1]]


 Take sync_tkt_route_name,sync_tkt_schedule_no,sync_tkt_trip_no,sync_tkt_start_stage_name,sync_tkt_end_stage_name as X

In [21]:
X=df3.iloc[:,[0,1,2,3,4]].values
print(X)

[['ANGLVLY-KTYM' 1 1 '8MILE' 'MANIMALA']
 ['ANGLVLY-KTYM' 1 1 '8MILE' 'PKALAM']
 ['ANGLVLY-KTYM' 1 1 'ALAMPALLY' 'KPARA']
 ...
 ['VAIKOM-PNCHKAD' 3 6 'VAIKOM' 'TALAYAZHOM']
 ['VAIKOM-PNCHKAD' 3 7 'VAIKOM' 'KAVANATNKAR']
 ['VAIKOM-PNCHKAD' 3 7 'VAIKOM' 'KOTTAYAM']]


 We want to Label encode sync_tkt_route_name,sync_tkt_start_stage_name,sync_tkt_end_stage_name

In [22]:
labelncoder=LabelEncoder()
X[:,0]=labelncoder.fit_transform(X[:,0])
X[:,3]=labelncoder.fit_transform(X[:,3])
X[:,4]=labelncoder.fit_transform(X[:,4])
print(X)

[[0 1 1 54 736]
 [0 1 1 54 1067]
 [0 1 1 71 582]
 ...
 [129 3 6 1300 1191]
 [129 3 7 1300 454]
 [129 3 7 1300 570]]


 By using Linear Regression

In [23]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3)
regressor=LinearRegression()
regressor.fit(X_train,Y_train)
y_pred=regressor.predict(X_test)
print('predictions: ',y_pred)

predictions:  [[4.12277105]
 [5.64553425]
 [5.33217828]
 ...
 [6.33836493]
 [2.75635776]
 [6.18445166]]


 These are the predicted values of Linear Regression.

In [24]:
print(y_pred)

[[4.12277105]
 [5.64553425]
 [5.33217828]
 ...
 [6.33836493]
 [2.75635776]
 [6.18445166]]


In [25]:
from sklearn.metrics import  r2_score
rl=r2_score(Y_test,y_pred)
print(rl)

0.01668427598499711


 By using Random Forest Regression

In [26]:
from sklearn.ensemble import RandomForestRegressor
model=RandomForestRegressor(n_estimators=100,random_state=40)
model.fit(X_train,Y_train)

<ipython-input-26-6de1f1032901>:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model.fit(X_train,Y_train)


RandomForestRegressor(random_state=40)

In [27]:
prediction_Random_Forest=model.predict(X_test)

Predicted values by using Random Forest Regression

In [28]:
print(prediction_Random_Forest)

[ 1.48  4.95 13.62 ...  7.06  2.61  3.26]


In [29]:
from sklearn.metrics import  r2_score
import numpy as np
r2 = r2_score(Y_test,prediction_Random_Forest)
print(r2)

0.1127310036185446


 By using Elastic Net

In [30]:
from sklearn.linear_model import ElasticNet
ela_reg=ElasticNet()
ela_reg.fit(X_train,Y_train)

ElasticNet()

In [31]:
ela_reg.fit(X_train,Y_train)

ElasticNet()

In [32]:
ela_predict=ela_reg.predict(X_test)

Predicted Values by using Elastic Net Regression

In [33]:
print(ela_predict)

[4.76127009 5.43818543 4.95485271 ... 5.81825725 4.01853775 5.71123939]


In [34]:
ela_score=r2_score(Y_test,ela_predict)
print(ela_score)

0.010592068929336285


By using Bagging Regression

In [35]:
from sklearn.ensemble import BaggingRegressor
bagging_regressor=BaggingRegressor()
bagging_regressor.fit(X_train,Y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


BaggingRegressor()

In [36]:
bagging_predictions=bagging_regressor.predict(X_test)

These are the predicted values by using Bagging Regression

In [37]:
print(bagging_predictions)

[ 1.6  4.5 17.2 ...  7.6  2.2  1.4]


In [38]:
Bagging_score=r2_score(Y_test,bagging_predictions)
print(Bagging_score)

0.05011479935170726


In [40]:
bagging_predictions

array([ 1.6,  4.5, 17.2, ...,  7.6,  2.2,  1.4])

We want to convert Y_test and Y_pred to 1D array for making DataFrame

In [41]:
import numpy as np
Y_test_1D_array=Y_test.flatten()

In [42]:
y_pred_1D_array=y_pred.flatten()

In [43]:
Y_true=Y_test_1D_array
Predicted_data={'True Sales of Ticket in diffrent Root' : Y_true,
         'Predicted Sales of Ticket in diffrent Root_ Linear Regression ': y_pred_1D_array,
         'Predicted Sales of Ticket in diffrent Root_ Random Forest Regression ': prediction_Random_Forest,
         'Predicted Sales of Ticket in diffrent Root_ Elastic Net Regression ': ela_predict,
         'Predicted Sales of Ticket in diffrent Root_Bagging Regression ': bagging_predictions,}
Predicted_data=pd.DataFrame(Predicted_data)
Predicted_data

True Sales of Ticket in diffrent Root  \
0                                          2   
1                                          5   
2                                          6   
3                                          3   
4                                          1   
...                                      ...   
13720                                      1   
13721                                      1   
13722                                      3   
13723                                      1   
13724                                      6   

       Predicted Sales of Ticket in diffrent Root_ Linear Regression   \
0                                               4.122771                
1                                               5.645534                
2                                               5.332178                
3                                               5.091129                
4                                               6.371768                
...                                                  ...                
13720                                           6.475410                
13721                                           6.314361                
13722                                           6.338365                
13723                                           2.756358                
13724                                           6.184452                

       Predicted Sales of Ticket in diffrent Root_ Random Forest Regression   \
0                                                   1.48                       
1                                                   4.95                       
2                                                  13.62                       
3                                                   8.13                       
4                                                   2.14                       
...                                                  ...                       
13720                                               6.70                       
13721                                               3.23                       
13722                                               7.06                       
13723                                               2.61                       
13724                                               3.26                       

       Predicted Sales of Ticket in diffrent Root_ Elastic Net Regression   \
0                                               4.761270                     
1                                               5.438185                     
2                                               4.954853                     
3                                               4.848816                     
4                                               5.570286                     
...                                                  ...                     
13720                                           5.936979                     
13721                                           5.631587                     
13722                                           5.818257                     
13723                                           4.018538                     
13724                                           5.711239                     

       Predicted Sales of Ticket in diffrent Root_Bagging Regression   
0                                                    1.6               
1                                                    4.5               
2                                                   17.2               
3                                                    7.8               
4                                                    1.1               
...                                                  ...               
13720                                                4.3               
13721                                                6.9               
13722  

In [44]:
Predicted_data.head()

True Sales of Ticket in diffrent Root  \
0                                      2   
1                                      5   
2                                      6   
3                                      3   
4                                      1   

   Predicted Sales of Ticket in diffrent Root_ Linear Regression   \
0                                           4.122771                
1                                           5.645534                
2                                           5.332178                
3                                           5.091129                
4                                           6.371768                

   Predicted Sales of Ticket in diffrent Root_ Random Forest Regression   \
0                                               1.48                       
1                                               4.95                       
2                                              13.62                       
3                                               8.13                       
4                                               2.14                       

   Predicted Sales of Ticket in diffrent Root_ Elastic Net Regression   \
0                                           4.761270                     
1                                           5.438185                     
2                                           4.954853                     
3                                           4.848816                     
4                                           5.570286                     

   Predicted Sales of Ticket in diffrent Root_Bagging Regression   
0                                                1.6               
1                                                4.5               
2                                               17.2               
3                                                7.8               
4                                                1.1

In [45]:
Predicted_data.tail()

True Sales of Ticket in diffrent Root  \
13720                                      1   
13721                                      1   
13722                                      3   
13723                                      1   
13724                                      6   

       Predicted Sales of Ticket in diffrent Root_ Linear Regression   \
13720                                           6.475410                
13721                                           6.314361                
13722                                           6.338365                
13723                                           2.756358                
13724                                           6.184452                

       Predicted Sales of Ticket in diffrent Root_ Random Forest Regression   \
13720                                               6.70                       
13721                                               3.23                       
13722                                               7.06                       
13723                                               2.61                       
13724                                               3.26                       

       Predicted Sales of Ticket in diffrent Root_ Elastic Net Regression   \
13720                                           5.936979                     
13721                                           5.631587                     
13722                                           5.818257                     
13723                                           4.018538                     
13724                                           5.711239                     

       Predicted Sales of Ticket in diffrent Root_Bagging Regression   
13720                                                4.3               
13721                                                6.9               
13722                                                7.6               
13723                                                2.2               
13724                                                1.4

In [46]:
Predicted_data[0:60]

True Sales of Ticket in diffrent Root  \
0                                       2   
1                                       5   
2                                       6   
3                                       3   
4                                       1   
5                                       2   
6                                       3   
7                                       1   
8                                       1   
9                                      12   
10                                      1   
11                                      1   
12                                      3   
13                                      1   
14                                      1   
15                                      4   
16                                      3   
17                                      1   
18                                      3   
19                                      7   
20                                      1   
21                                     40   
22                                      1   
23                                      1   
24                                      1   
25                                     63   
26                                      6   
27                                      1   
28                                      3   
29                                      5   
30                                      1   
31                                      1   
32                                      3   
33                                      2   
34                                      2   
35                                      3   
36                                      1   
37                                      2   
38                                      1   
39                                      2   
40                                      3   
41                                      1   
42                                      1   
43                                      5   
44                                     14   
45                                      1   
46                                      7   
47                                      1   
48                                      9   
49                                      1   
50                                      1   
51                                      9   
52                                      6   
53                                      4   
54                                      1   
55                                     17   
56                                      1   
57                                      1   
58                                      2   
59                                      3   

    Predicted Sales of Ticket in diffrent Root_ Linear Regression   \
0                                            4.122771                
1                                            5.645534                
2                                            5.332178                
3                                            5.091129                
4                                            6.371768                
5                                            5.962563                
6                                            4.980488                
7                                            5.974804                
8                                            3.850261                
9                                            5.012911                
10                                           0.566943                
11                                           4.840474                
12                                           5.875378                
13                                           3.378579                
14                                           4.595169                
15                                           4.452291                
16                                           3.340442               